//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingJewellery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int NorR { get; set; }
        public string UserID { get; set; }
        public string country { get; set; }
        public string state_province { get; set; }
        public string city { get; set; }
        public string Address1 { get; set; }
        public string Zip_Postal { get; set; }
        public string Instruction_Optional { get; set; }
        public bool default_address { get; set; }
    
        public virtual UserRegMst UserRegMst { get; set; }
    }
}
