//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingJewellery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int ID_Deliver { get; set; }
        public int ID_Order { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime Date_Sent { get; set; }
        public System.DateTime Date_Deliver_estimate { get; set; }
        public string CodeTracking { get; set; }
    
        public virtual Order_ Order_ { get; set; }
    }
}
