//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingJewellery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimMst
    {
        public string Style_Code { get; set; }
        public string DimQlty_ID { get; set; }
        public string DimSubType_ID { get; set; }
        public decimal Dim_Crt { get; set; }
        public decimal Dim_Pcs { get; set; }
        public decimal Dim_Gm { get; set; }
        public decimal Dim_Size { get; set; }
        public decimal Dim_Rate { get; set; }
        public decimal Dim_Amt { get; set; }
        public int No { get; set; }
        public decimal Dim_CrtSub { get; set; }
        public decimal Dim_PcsSub { get; set; }
        public decimal Dim_GmSub { get; set; }
        public decimal Dim_SizeSub { get; set; }
        public decimal Dim_RateSub { get; set; }
        public decimal Dim_AmtSub { get; set; }
        public decimal Total_AmtAll { get; set; }
    
        public virtual DimQltyMst DimQltyMst { get; set; }
        public virtual DimQltySubMst DimQltySubMst { get; set; }
        public virtual ItemMst ItemMst { get; set; }
    }
}
