//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingJewellery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FId { get; set; }
        public string cDate { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public string ReDate { get; set; }
        public string ReComment { get; set; }
    
        public virtual UserRegMst UserRegMst { get; set; }
    }
}
