//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingJewellery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquiry
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string EmailID { get; set; }
        public string Comment { get; set; }
        public System.DateTime Cdate { get; set; }
    }
}
