//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingJewellery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Require
    {
        public string Style_Code { get; set; }
        public int Diamon_No { get; set; }
        public int Stone_No { get; set; }
        public int Size { get; set; }
        public decimal Total { get; set; }
        public int ID { get; set; }
        public int Gold_No { get; set; }
    
        public virtual ItemMst ItemMst { get; set; }
    }
}
