//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingJewellery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int ID_Order { get; set; }
        public string Style_code { get; set; }
        public int Gold_No { get; set; }
        public int Diamond_No { get; set; }
        public int Stone_No { get; set; }
        public int Size { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public decimal Total { get; set; }
        public int ID { get; set; }
    
        public virtual ItemMst ItemMst { get; set; }
        public virtual Order_ Order_ { get; set; }
    }
}
