//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingJewellery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string TypeCreditCard { get; set; }
        public string Method_Card { get; set; }
        public string CardNumber { get; set; }
        public int ID_Order { get; set; }
        public string NameOnCard { get; set; }
        public string CVV_CVC { get; set; }
        public System.DateTime Expiry_Date { get; set; }
        public int ID_Payment { get; set; }
    
        public virtual Order_ Order_ { get; set; }
    }
}
