//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingJewellery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductView
    {
        public string Style_Code { get; set; }
        public decimal Quantity { get; set; }
        public decimal Tot_Gross_Wt { get; set; }
        public string Img { get; set; }
        public string Cat_Name { get; set; }
        public string Brand_Type { get; set; }
        public string Certify_Type { get; set; }
        public string Prod_Type { get; set; }
        public string Jewellery_Type { get; set; }
    }
}
