//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingJewellery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receiver
    {
        public int ID { get; set; }
        public string Name_Receiver { get; set; }
        public System.DateTime Date_receive { get; set; }
        public string Address_receive { get; set; }
        public int ID_Order { get; set; }
    
        public virtual Order_ Order_ { get; set; }
    }
}
