//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingJewellery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegMst
    {
        public string userID { get; set; }
        public string userFname { get; set; }
        public string userLname { get; set; }
        public string mobNo { get; set; }
        public string emailID { get; set; }
        public string dob { get; set; }
        public string cdate { get; set; }
        public string password { get; set; }
    }
}
