//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingJewellery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFullItem
    {
        public string Style_Code { get; set; }
        public string Img { get; set; }
        public decimal Pairs { get; set; }
        public string Cat_ID { get; set; }
        public string Prod_ID { get; set; }
        public string JewelleryType_ID { get; set; }
        public string Brand_ID { get; set; }
        public string Certify_ID { get; set; }
        public decimal Quantity { get; set; }
        public string Prod_Quality { get; set; }
        public decimal Net_Gold { get; set; }
        public decimal Tot_Gross_Wt { get; set; }
        public decimal Stone_Making { get; set; }
        public decimal Gold_Making { get; set; }
        public decimal Other_Making { get; set; }
        public decimal Tot_Making { get; set; }
        public int size { get; set; }
        public decimal MRP { get; set; }
        public decimal Stone_Wt { get; set; }
        public string Cat_Name { get; set; }
        public string Prod_Type { get; set; }
        public string Brand_Type { get; set; }
        public string Jewellery_Type { get; set; }
        public string Certify_Type { get; set; }
        public Nullable<int> No_Gold { get; set; }
        public string GoldType_ID { get; set; }
        public string Gold_Crt { get; set; }
        public Nullable<decimal> Gold_Rate { get; set; }
        public Nullable<decimal> Gold_Wt { get; set; }
        public Nullable<decimal> Wstg_Per { get; set; }
        public Nullable<decimal> Wstq { get; set; }
        public Nullable<decimal> Total_weight { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<int> No_Diamond { get; set; }
        public string DimQlty_ID { get; set; }
        public string MainType { get; set; }
        public Nullable<decimal> Dim_Crt { get; set; }
        public Nullable<decimal> Dim_Pcs { get; set; }
        public Nullable<decimal> Dim_Gm { get; set; }
        public Nullable<decimal> Dim_Size { get; set; }
        public Nullable<decimal> Dim_Rate { get; set; }
        public Nullable<decimal> Dim_Amt { get; set; }
        public string DimSubType_ID { get; set; }
        public string SubTyle { get; set; }
        public Nullable<decimal> Dim_CrtSub { get; set; }
        public Nullable<decimal> Dim_PcsSub { get; set; }
        public Nullable<decimal> Dim_GmSub { get; set; }
        public Nullable<decimal> Dim_SizeSub { get; set; }
        public Nullable<decimal> Dim_RateSub { get; set; }
        public Nullable<decimal> Dim_AmtSub { get; set; }
        public Nullable<decimal> Total_AmtAll { get; set; }
        public Nullable<int> No_Stone { get; set; }
        public string StoneQlty_ID { get; set; }
        public string StoneQlty { get; set; }
        public Nullable<decimal> Stone_Gm { get; set; }
        public Nullable<decimal> Stone_Pcs { get; set; }
        public Nullable<decimal> Stone_Crt { get; set; }
        public Nullable<decimal> Stone_Rate { get; set; }
        public Nullable<decimal> Stone_Amt { get; set; }
        public Nullable<decimal> total_brand { get; set; }
    }
}
