//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingJewellery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDisplayItem
    {
        public string Style_Code { get; set; }
        public string Img { get; set; }
        public Nullable<decimal> Total_weight { get; set; }
        public string image { get; set; }
        public decimal Tot_Gross_Wt { get; set; }
        public string GoldType_ID { get; set; }
        public string Gold_Crt { get; set; }
        public string Prod_ID { get; set; }
        public string Prod_Type { get; set; }
        public string Brand_ID { get; set; }
        public string Cat_ID { get; set; }
        public string Cat_Name { get; set; }
        public string Jewellery_Type { get; set; }
        public string JewelleryType_ID { get; set; }
        public string Brand_Type { get; set; }
        public Nullable<decimal> total_brand { get; set; }
    }
}
